PUT http://localhost:3001/api/blogs/64c88607f38605c6d78ae98e HTTP/1.1
content-type: application/json

{
  "id": "64c88607f38605c6d78ae98e",
  "title": "E4, envidia, especial",
  "author": "Yo mismo",
  "url": "www.google.es",
  "likes": 10
}